### ISSUE TITLE
I do not find this project in maven

### ISSUE THREAD

**Issue by damianopetrungaro** [parsix/parsix#4]
Hello @iazel, great work on the library!
I do not see it available in the maven repository, any recommendation?

**Comment by iazel** [comment]
Hi @damianopetrungaro , happy to hear you are interested. I'll try to push it to maven central, I think it will be there around next week.

**Comment by damianopetrungaro** [comment]
Thanks @iazel, I think this project would have way more traction if we let software engineers use it as a dep.

**Comment by iazel** [comment]
Hello again, the package is now available in `mavenCentral` with version 0.1.0

I've updated the README with instructions on how to set it up, enjoy! ;)
